service: tnm-malawi-refund-get-status
frameworkVersion: ^3.3.0
configValidationMode: error

custom:
  functionName: ${self:service}
  functionHandler: get-status
  mainSecretName: ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):environment_variables.secret_name}
  MainQueue: ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):queues.main_queue}


provider:
  name: aws
  region: eu-west-1
  stackName: ${self:custom.functionName}
  deploymentBucket:
    name: com.serverless.${self:provider.region}.${aws:accountId, '427246389222'}.dpo.deploys
    blockPublicAccess: true
  deploymentPrefix: dpoafrica/mno/lambda
  iam:
    role:
      managedPolicies:
        - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):policies.dpoServices}
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource:
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):secrets.main}
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):secrets.db_process}
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):secrets.db_africainv}
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):secrets.cache}
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):secrets.dpo_services}
        - Effect: "Allow"
          Action:
            - "sqs:GetQueueUrl"
            - "sqs:SendMessage"
            - "sqs:GetQueueAttributes"
          Resource:
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):queues.main_queue}
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):queues.dpo_mail_sender}
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):queues.mgmt_email_sender}
        - Effect: "Allow"
          Action:
            - "sqs:DeleteMessage"
            - "sqs:ReceiveMessage"
          Resource:
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):queues.main_queue}

package:
  patterns:
    - "!.serverless"
    - "!.deploy"
    - "!.idea"
    - "!cache"
    - "!enums"
    - "!logger"
    - "!models"
    - "!process"
    - "!repository"
    - "!request"
    - "!utils"
    - "README.md"
    - "!sonar-project.properties"
    - "!ascii.txt"
    - "!go.*"
    - "!*.go"
    - "!appspec.yml"
    - "!serverless.yml"
    - "!.gitlab-ci.yml"
    - "!.gitignore"
    - "!docker-compose.yml"
    - "!Dockerfile"
    - ${self:custom.functionName}

functions:
  MainFunction:
    handler: ${self:custom.functionHandler}
    name: ${self:custom.functionName}
    description: Tnm Malawi check status
    runtime: go1.x
    architecture: x86_64
    memorySize: 128
    timeout: 30
    tags:
      Stack: dpo-callback-process
    environment:
      LOG_LEVEL: DEBUG
      SECRET_NAME: ${self:custom.mainSecretName}
    vpc: ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):vpc}
    events:
      - sqs:
          arn: ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):queues.main_queue}
          batchSize: 1
          maximumBatchingWindow: 0